### ISSUE TITLE
Preparations for Hacktoberfest

### ISSUE THREAD

**Issue by pwochner** [Herb-AI/Herb.jl#103]
- [ ] Tag existing issues that are suitable with `good first issue` and `Hacktoberfest` to make sure they give sufficient context and contain all relevant information.
- [ ] Open new issues if you have an idea. 
- [ ] Add issues to the Hacktoberfest umbrella issue: #102 
- [x] Add `hacktoberfest` tag to repo
- [ ] Make sure Herb appears on [this Hacktoberfest site](https://juliacommunity.github.io/your-first-julia-pr/) dedicated to Julia projects
- [ ] Make #102 more fun and inviting.

**Comment by sebdumancic** [comment]
two ideas for more advanced Julia users:
 - [ ] look into [DynamicExpressions.jl](https://github.com/SymbolicML/DynamicExpressions.jl) to improve the evaluation of expressions
 - [ ] add interpreters to a favourite programming language (Python, LISP family member, Java,...).
