### ISSUE TITLE
Add context-sensitive grammars

### ISSUE THREAD

**Issue by jaapdejong15** [Herb-AI/Herb.jl#25]
Add context-sensitive grammars to Grammar.jl.
(Parts of) functionality can be copied from [ExprRules](https://github.com/Herb-AI/ExprRules.jl).
Also see https://github.com/Herb-AI/Search.jl/pull/4#discussion_r1097058513.

**Comment by sebdumancic** [comment]
The iterators should work the same as in context-free grammar, just call some function to propagate constraints at every expansion (basically filter viable candidates), as in here: https://github.com/Herb-AI/ExprRules.jl/blob/master/src/csgrammar/iterators.jl#L48

The function for propagating constraints: https://github.com/Herb-AI/ExprRules.jl/blob/master/src/csgrammar/iterators.jl#L4
