### ISSUE TITLE
New repo: Search.jl

### ISSUE THREAD

**Issue by jaapdejong15** [Herb-AI/Herb.jl#3]
This repo should contain implementations of search procedures over grammar expressions (BFS, DFS, A*, ...)

Core functionality:
 - [ ] Depth-first search and breadth-first search implementations
 - [ ] Write the expansion step in a different file: the input is the current state and the output is the set of possible children

Desired Functionality:
 - [ ] Nice abstracted search template: state manipulation
 - [ ] Search algorithms: A*, Metropolis-Hastings, Very Large Neighbourhood Search, Monte Carlo Tree Search, Genetic algorithms

Interfacing with other packages:
 - take a grammar definition from Grammar.jl,
 - takes Heuristics.jl
 - takes ConstraintsLib.jl
 - takes Specification.jl
 - takes LearningToSearch.jl

@THinnerichs and @jaapdejong15 will make the template, and @piotr-cichon and @nickk2002 will focus on the other search functionalities

**Comment by sebdumancic** [comment]
plan to incorporate user interaction in search
